pytest:
  stage: test
  image: yourlabs/python
  script:
  - pip install .
  - py.test -v
  services:
  - name: yourlabs/tezos
    alias: tz

pypi:
  stage: deploy
  image: yourlabs/python
  script: pypi-release
